### ISSUE TITLE
HGNC version out of date: missing 2023-03-02

### ISSUE THREAD

**Issue by dhimmel** [biopragmatics/bioversions#30]
Looking at https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/monthly/json/, the most recent monthly HGNC release is `hgnc_complete_set_2023-03-02.json`. But I don't see this or other recent versions in bioversions:

https://github.com/biopragmatics/bioversions/blob/792fd7bee02ee5c69a762b65f46ef2a38cf7095f/docs/_data/versions.yml#L1851-L1862

Don't immediately see any problems in [`src/bioversions/sources/hgnc.py`](https://github.com/biopragmatics/bioversions/blob/792fd7bee02ee5c69a762b65f46ef2a38cf7095f/src/bioversions/sources/hgnc.py).

**Comment by cthoyt** [comment]
Looks like some changes in tox caused the nightly script to stop working. Testing a fix now

**Comment by cthoyt** [comment]
Fixed in https://github.com/biopragmatics/bioversions/commit/867b2ff18e4252cab93812dbbf3034a8117199bc
