### ISSUE TITLE
No connection adapters were found for 'ftp://ftp.expasy.org/databases/rhea/rhea-release.properties'

### ISSUE THREAD

**Issue by hrshdhgd** [biopragmatics/bioversions#39]
This error is not consistent and happens abruptly with no pattern. Here's what's going on:

I'm trying to get the relations dataframe through `pyobo` using
```
  rhea_relation = get_relations_df("rhea")
```

This in turn calls 
```
    version = get_version(prefix)
```

`get_version()` in pyobo looks like this

```
def get_version(prefix: str) -> Optional[str]:
    """Get the version for the resource, if available.

    :param prefix: the resource name
    :return: The version if available else None
    """
    try:
        version = bioversions.get_version(prefix)
    except KeyError:
        pass  # this prefix isn't available from bioversions
    except Exception as e:
        raise ValueError(f"[{prefix}] could not get version from bioversions") from e
    else:
        if version:
            return version
```

When `prefix` == `rhea` it throws the following error:

```
*** requests.exceptions.InvalidSchema: No connection adapters were found for 'ftp://ftp.expasy.org/databases/rhea/rhea-release.properties'
```

Again, this does not happen consistently but does happen. It happened on my system (multiple times) as well as a colleague's system at a different time. I cannot pin-point what the reason could be. Any thoughts @cthoyt ?

**Comment by cthoyt** [comment]
not sure what's going on here. requests_ftp gets imported and monkeypatched in the rhea module: https://github.com/biopragmatics/bioversions/blob/88246fe5acef460ea86ec44731ce8e3d45d94263/src/bioversions/sources/rhea.py#L14

**Comment by cthoyt** [comment]
We could switch the URL to https://ftp.expasy.org/databases/rhea/rhea-release.properties and it would still work. That might be the safest solution

**Comment by hrshdhgd** [comment]
I agree. Testing it right now. The only way I could make it work with `ftp:/` was if I called `requests_ftp.monkeypatch_session()` right before `get_relations_df()` call in my project. Not sure if it is an optimal solution.

**Comment by hrshdhgd** [comment]
.. and that worked!

**Comment by hrshdhgd** [comment]
https://github.com/biopragmatics/bioversions/pull/40
